services:
  postgres:
    image: postgres:15-alpine
    container_name: unihub-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: unihub_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      # - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis-rate:
    image: redis:7-alpine
    container_name: unihub-redis-rate
    ports:
      - "6380:6379"
    command: redis-server --save "" --appendonly no

  redis-lock:
    image: redis:7-alpine
    container_name: unihub-redis-lock
    ports:
      - "6381:6379"
    command: redis-server --appendonly yes

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: unihub-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.0
    container_name: unihub-keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/unihub_db
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: password
    command: start-dev --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm.json
    depends_on:
      - postgres

  gateway:
    build: ./gateway
    ports:
      - "80:80"
    depends_on:
      - redis-rate
      - keycloak
      - backend1
      - backend2
      - backend3

  backend1:
    build: ./backend-core
    container_name: unihub-backend-1
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/unihub_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATA_REDIS_HOST=redis-lock
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://localhost:8080/realms/unihub
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/unihub/protocol/openid-connect/certs
    depends_on:
      - postgres
      - redis-lock
      - rabbitmq
      - keycloak

  backend2:
    build: ./backend-core
    container_name: unihub-backend-2
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/unihub_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATA_REDIS_HOST=redis-lock
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://localhost:8080/realms/unihub
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/unihub/protocol/openid-connect/certs
    depends_on:
      - postgres
      - redis-lock
      - rabbitmq
      - keycloak

  backend3:
    build: ./backend-core
    container_name: unihub-backend-3
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/unihub_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATA_REDIS_HOST=redis-lock
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://localhost:8080/realms/unihub
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/unihub/protocol/openid-connect/certs
    depends_on:
      - postgres
      - redis-lock
      - rabbitmq
      - keycloak

  sync-service:
    build: ./sync-service
    container_name: unihub-sync-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/unihub_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - APP_KEYCLOAK_SERVER_URL=http://keycloak:8080
      - APP_KEYCLOAK_REALM=unihub
      - APP_KEYCLOAK_CLIENT_ID=user-sync-service
      - APP_KEYCLOAK_CLIENT_SECRET=super-secure-sync-secret-123
      - APP_SYNC_CSV_PATH=/data
      - APP_SYNC_ARCHIVE_PATH=/data/archive
    volumes:
      - ./data:/data
    depends_on:
      - postgres
      - keycloak

  frontend:
    build: ./frontend
    container_name: unihub-frontend
    ports:
      - "3000:80"
    depends_on:
      - gateway

  adminer:
    image: adminer
    container_name: unihub-adminer
    restart: always
    ports:
      - 8082:8080

volumes:
  postgres_data:
