-- Seed data intentionally excludes students.
-- Students are imported from the legacy CSV pipeline and synchronized to Keycloak.

INSERT INTO workshops (
    id,
    name,
    description,
    speaker,
    speaker_title,
    topic,
    room,
    room_map_text,
    tags,
    organizer_id,
    max_seats,
    available_slots,
    registration_start_time,
    registration_end_time,
    start_time,
    end_time,
    is_paid,
    price,
    status,
    summary_text,
    summary_status
) VALUES
(
    '11111111-1111-1111-1111-111111111111',
    'Spring Boot Microservices',
    'Thiết kế service Spring Boot, giao tiếp REST/RabbitMQ, cấu hình Docker và tách miền nghiệp vụ cho hệ thống chịu tải cao.',
    'Nguyễn Hoàng Nam',
    'Senior Backend Engineer',
    'Backend',
    'A101',
    'Tòa A, tầng 1, phòng bên phải sảnh chính.',
    '["Java", "Spring Boot", "Microservices", "RabbitMQ"]'::jsonb,
    'organizer-demo',
    60,
    60,
    CURRENT_TIMESTAMP - INTERVAL '1 day',
    CURRENT_TIMESTAMP + INTERVAL '6 days',
    CURRENT_TIMESTAMP + INTERVAL '7 days 8 hours',
    CURRENT_TIMESTAMP + INTERVAL '7 days 9 hours 30 minutes',
    false,
    0,
    'ACTIVE',
    'Workshop giới thiệu cách chia nhỏ hệ thống Java thành các service độc lập, dùng RabbitMQ cho xử lý bất đồng bộ và Docker để chạy môi trường nhất quán.',
    'COMPLETED'
),
(
    '22222222-2222-2222-2222-222222222222',
    'Advanced AI in Practice',
    'Ứng dụng AI vào phân tích tài liệu, tạo tóm tắt, đánh giá prompt và xây dựng luồng xử lý có kiểm soát lỗi.',
    'Trần Minh Anh',
    'AI Solution Architect',
    'AI',
    'B202',
    'Tòa B, tầng 2, gần khu tự học.',
    '["AI", "LLM", "Prompt Engineering", "PDF"]'::jsonb,
    'organizer-demo',
    40,
    40,
    CURRENT_TIMESTAMP - INTERVAL '1 day',
    CURRENT_TIMESTAMP + INTERVAL '6 days',
    CURRENT_TIMESTAMP + INTERVAL '7 days 10 hours',
    CURRENT_TIMESTAMP + INTERVAL '7 days 11 hours 30 minutes',
    true,
    100000,
    'ACTIVE',
    'Buổi học tập trung vào cách đưa AI vào quy trình thực tế: trích xuất nội dung, làm sạch dữ liệu, gọi mô hình và lưu kết quả an toàn.',
    'COMPLETED'
),
(
    '33333333-3333-3333-3333-333333333333',
    'React Frontend Performance',
    'Tối ưu giao diện React cho trang danh sách workshop, giảm render thừa, cải thiện trải nghiệm trên thiết bị di động.',
    'Lê Gia Bảo',
    'Frontend Lead',
    'Frontend',
    'C303',
    'Tòa C, tầng 3, phòng lab màn hình lớn.',
    '["React", "Vite", "Performance", "UX"]'::jsonb,
    'organizer-demo',
    80,
    80,
    CURRENT_TIMESTAMP - INTERVAL '1 day',
    CURRENT_TIMESTAMP + INTERVAL '7 days',
    CURRENT_TIMESTAMP + INTERVAL '8 days 8 hours',
    CURRENT_TIMESTAMP + INTERVAL '8 days 9 hours 30 minutes',
    false,
    0,
    'ACTIVE',
    NULL,
    'PENDING'
),
(
    '44444444-4444-4444-4444-444444444444',
    'Data Science với Python',
    'Thực hành xử lý dữ liệu bằng Pandas, trực quan hóa nhanh và xây dựng mô hình phân loại cơ bản với scikit-learn.',
    'Phạm Thu Hà',
    'Data Scientist',
    'Data',
    'D404',
    'Tòa D, tầng 4, phòng máy số 4.',
    '["Python", "Pandas", "Data Science", "scikit-learn"]'::jsonb,
    'organizer-demo',
    45,
    45,
    CURRENT_TIMESTAMP - INTERVAL '1 day',
    CURRENT_TIMESTAMP + INTERVAL '7 days',
    CURRENT_TIMESTAMP + INTERVAL '8 days 13 hours',
    CURRENT_TIMESTAMP + INTERVAL '8 days 15 hours',
    true,
    150000,
    'ACTIVE',
    NULL,
    'PENDING'
),
(
    '55555555-5555-5555-5555-555555555555',
    'Kỹ năng Phỏng vấn IT',
    'Mô phỏng phỏng vấn kỹ thuật, cách trình bày dự án cá nhân và trả lời câu hỏi hành vi cho sinh viên công nghệ.',
    'Vũ Đức Long',
    'Engineering Manager',
    'Career',
    'E505',
    'Tòa E, tầng 5, phòng hội thảo nghề nghiệp.',
    '["Interview", "Career", "CV", "Communication"]'::jsonb,
    'organizer-demo',
    100,
    100,
    '2026-05-10 08:00:00+07',
    '2026-05-19 23:59:00+07',
    '2026-05-20 08:30:00+07',
    '2026-05-20 10:00:00+07',
    false,
    0,
    'ACTIVE',
    'Workshop giúp sinh viên chuẩn bị phỏng vấn IT bằng cách luyện trình bày kinh nghiệm, xử lý câu hỏi kỹ thuật và nhận phản hồi trực tiếp.',
    'COMPLETED'
),
(
    '66666666-6666-6666-6666-666666666666',
    'Cloud Computing cơ bản',
    'Tổng quan cloud, container, database managed service và cách triển khai một ứng dụng web nhỏ lên môi trường cloud.',
    'Đặng Quốc Huy',
    'Cloud Architect',
    'Cloud',
    'F606',
    'Tòa F, tầng 6, phòng lab cloud.',
    '["Cloud", "Docker", "Deployment", "DevOps"]'::jsonb,
    'organizer-demo',
    50,
    50,
    '2026-05-10 08:00:00+07',
    '2026-05-19 23:59:00+07',
    '2026-05-20 10:30:00+07',
    '2026-05-20 12:00:00+07',
    false,
    0,
    'ACTIVE',
    NULL,
    'PENDING'
),
(
    '77777777-7777-7777-7777-777777777777',
    'Cyber Security Fundamentals',
    'Nhận diện lỗ hổng phổ biến, cách phòng chống tấn công web cơ bản và thực hành kiểm tra bảo mật API.',
    'Hoàng Gia Phúc',
    'Security Analyst',
    'Security',
    'G707',
    'Tòa G, tầng 7, phòng an toàn thông tin.',
    '["Security", "OWASP", "API", "Web"]'::jsonb,
    'organizer-demo',
    35,
    35,
    '2026-05-10 08:00:00+07',
    '2026-05-20 23:59:00+07',
    '2026-05-21 08:30:00+07',
    '2026-05-21 10:30:00+07',
    true,
    200000,
    'ACTIVE',
    NULL,
    'PENDING'
),
(
    '88888888-8888-8888-8888-888888888888',
    'Offline-first Mobile Check-in',
    'Thiết kế quy trình quét QR hoạt động khi mất mạng, lưu cục bộ và đồng bộ lại lên server khi kết nối phục hồi.',
    'Bùi Khánh Linh',
    'Mobile Engineer',
    'Mobile',
    'H808',
    'Tòa H, tầng 8, khu demo mobile.',
    '["Android", "Offline-first", "QR", "Sync"]'::jsonb,
    'organizer-demo',
    55,
    55,
    '2026-05-10 08:00:00+07',
    '2026-05-20 23:59:00+07',
    '2026-05-21 13:30:00+07',
    '2026-05-21 15:00:00+07',
    false,
    0,
    'ACTIVE',
    'Nội dung tập trung vào store-and-forward, xử lý quét trùng, bảo toàn timestamp gốc và đồng bộ hàng loạt sau khi có mạng.',
    'COMPLETED'
),
(
    '99999999-9999-9999-9999-999999999999',
    'Payment Reliability Patterns',
    'Thiết kế luồng thanh toán có idempotency key, timeout window, webhook và circuit breaker để tránh trừ tiền hai lần.',
    'Ngô Minh Quân',
    'Payment Platform Engineer',
    'Payment',
    'I909',
    'Tòa I, tầng 9, phòng seminar fintech.',
    '["Payment", "Idempotency", "Circuit Breaker", "Webhook"]'::jsonb,
    'organizer-demo',
    45,
    45,
    '2026-05-10 08:00:00+07',
    '2026-05-21 23:59:00+07',
    '2026-05-22 08:30:00+07',
    '2026-05-22 10:00:00+07',
    true,
    120000,
    'ACTIVE',
    'Workshop giải thích cách xây dựng thanh toán an toàn: mỗi giao dịch xử lý đúng một lần, lỗi gateway được cô lập và webhook được kiểm chứng.',
    'COMPLETED'
),
(
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    'Workshop đã hủy - Demo đổi lịch',
    'Bản ghi dùng để kiểm tra UI và API khi workshop bị hủy nhưng vẫn cần giữ lịch sử quản trị.',
    'Ban tổ chức UniHub',
    'Organizer Team',
    'Operations',
    'Z001',
    'Phòng demo trạng thái hủy.',
    '["Cancelled", "Admin", "Demo"]'::jsonb,
    'organizer-demo',
    30,
    0,
    '2026-05-10 08:00:00+07',
    '2026-05-21 23:59:00+07',
    '2026-05-22 13:30:00+07',
    '2026-05-22 15:00:00+07',
    false,
    0,
    'CANCELLED',
    NULL,
    'PENDING'
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    speaker = EXCLUDED.speaker,
    speaker_title = EXCLUDED.speaker_title,
    topic = EXCLUDED.topic,
    room = EXCLUDED.room,
    room_map_text = EXCLUDED.room_map_text,
    tags = EXCLUDED.tags,
    organizer_id = EXCLUDED.organizer_id,
    max_seats = EXCLUDED.max_seats,
    available_slots = EXCLUDED.available_slots,
    registration_start_time = EXCLUDED.registration_start_time,
    registration_end_time = EXCLUDED.registration_end_time,
    start_time = EXCLUDED.start_time,
    end_time = EXCLUDED.end_time,
    is_paid = EXCLUDED.is_paid,
    price = EXCLUDED.price,
    status = EXCLUDED.status,
    summary_text = EXCLUDED.summary_text,
    summary_status = EXCLUDED.summary_status,
    updated_at = CURRENT_TIMESTAMP;
