spring.main.web-application-type=none
spring.application.name=worker
spring.threads.virtual.enabled=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_ADDRESS}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Tùy chọn: Tự động tạo bảng từ code Java
# Server configuration
server.port=8082

# Database configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/unihub_db
spring.datasource.username=admin
spring.datasource.password=password
# Lưu ý: Thêm dòng này để chắc chắn Spring nhận diện đúng driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# OpenAI / OpenRouter Configuration
spring.ai.openai.api-key=${OPENROUTER_API_KEY}
spring.ai.openai.base-url=https://openrouter.ai/api
spring.ai.openai.chat.options.model=gpt-4o-mini
# Ép Worker chỉ xử lý đúng 1 tin nhắn tại một thời điểm
spring.rabbitmq.listener.simple.concurrency=1
spring.rabbitmq.listener.simple.max-concurrency=1
# Giới hạn số tin nhắn lấy về từ server (Prefetch)
spring.rabbitmq.listener.simple.prefetch=1

# # Redis configuration
# spring.data.redis.host=localhost
# spring.data.redis.port=6381

# # RabbitMQ configuration
# spring.data.rabbitmq.host=localhost
# spring.data.rabbitmq.port=5672
# spring.data.rabbitmq.username=guest
# spring.data.rabbitmq.password=guest

# # Security OAuth2 configuration
# spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/unihub

# # Resilience4j Circuit Breaker configuration
# resilience4j.circuitbreaker.instances.paymentGateway.registerHealthIndicator=true
# resilience4j.circuitbreaker.instances.paymentGateway.slidingWindowSize=20
# resilience4j.circuitbreaker.instances.paymentGateway.failureRateThreshold=50
# resilience4j.circuitbreaker.instances.paymentGateway.waitDurationInOpenState=30s
# resilience4j.circuitbreaker.instances.paymentGateway.permittedNumberOfCallsInHalfOpenState=3
# resilience4j.circuitbreaker.instances.paymentGateway.minimumNumberOfCalls=10

# Disable Spring AI Retry to save quota
spring.ai.retry.max-attempts=1
spring.ai.retry.initial-interval=1000
spring.ai.retry.multiplier=1.0