worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/json;

    resolver 127.0.0.11; # Docker DNS

    upstream backend {
        server host.docker.internal:8081; # Core API
    }

    server {
        listen       80;
        server_name  localhost;

        location /api/ {
            access_by_lua_file /etc/nginx/lua/rate_limit.lua;
            
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /health {
            return 200 '{"status":"UP"}';
        }
    }
}
