server:
  port: 8081

spring:
  application:
    name: backend-core
  datasource:
    url: jdbc:postgresql://localhost:5432/unihub_db
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6381 # Using redis-lock as primary for business logic
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/unihub

resilience4j:
  circuitbreaker:
    instances:
      paymentGateway:
        registerHealthIndicator: true
        slidingWindowSize: 20
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 10